### ISSUE TITLE
[QUESTION] is there anything like `@app.callback` to do a after-command execution cleanup?

### ISSUE THREAD

**Issue by prutheus** [fastapi/typer#307]
I use `@app.callback` to init my app.

I am wondering now if there is any common way to implement a post-execution-method/handler to finally cleanup some stuff which got initialised in the callback after the app executed the command?

Please let me know.

**Comment by captainCapitalism** [comment]
I haven't stumbled upon anything like that in Typer. Click recomends using Python's native context managers to do so:     https://click.palletsprojects.com/en/8.0.x/advanced/#managing-resources

There is an example of how to use it with click.Context, that however you cannot use, because it looks to me that it was introduced in click 8.0, where typer uses click 7.1, so you could use native `with` statement.

**Comment by captainCapitalism** [comment]
I found out that `Typer` class has an argument of `result_callback`.  It seems that is just used as a `result_callback` from `Click`.

https://click.palletsprojects.com/en/7.x/api/#click.MultiCommand

I am attaching a working example:
```python
import typer


def result(executed_command_result):
    print("HELLO AFTER COMMAND")
    print("Function returned: ", executed_command_result)


app = typer.Typer(result_callback=result)


@app.callback()
def cb():
    print("HELLO BEFORE COMMAND")


@app.command()
def cmd():
    print("HELLO IN COMMAND")

    return 44


if __name__ == "__main__":
    app()
```
